

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.7


stages:
  - build
  - test


before_script:
    - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy homework/

black:
  stage: test
  script:
    - black --diff --check homework/

isort:
  stage: test
  script:
    - isort --check-only homework/

flask8:
  stage: test
  script:
    - flake8 homework/